import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { cn } from "../lib/utils";
export function SkeletonCard({ className, children }) {
    return (_jsx("div", { className: cn("bg-card border border-border rounded-lg p-6", className), children: _jsxs("div", { className: "animate-pulse space-y-4", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("div", { className: "h-6 bg-muted rounded w-1/3" }), _jsx("div", { className: "h-4 bg-muted rounded w-16" })] }), _jsxs("div", { className: "space-y-3", children: [_jsx("div", { className: "h-4 bg-muted rounded w-full" }), _jsx("div", { className: "h-4 bg-muted rounded w-5/6" }), _jsx("div", { className: "h-4 bg-muted rounded w-4/6" })] }), _jsxs("div", { className: "flex gap-4 pt-4", children: [_jsx("div", { className: "h-8 bg-muted rounded w-20" }), _jsx("div", { className: "h-8 bg-muted rounded w-24" })] }), children] }) }));
}
export function SkeletonTable() {
    return (_jsxs("div", { className: "bg-card border border-border rounded-lg overflow-hidden", children: [_jsx("div", { className: "p-4 border-b border-border", children: _jsx("div", { className: "h-6 bg-muted rounded w-1/4 animate-pulse" }) }), _jsx("div", { className: "divide-y divide-border", children: Array.from({ length: 5 }).map((_, i) => (_jsx("div", { className: "p-4 animate-pulse", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "w-8 h-8 bg-muted rounded-full" }), _jsxs("div", { className: "space-y-2", children: [_jsx("div", { className: "h-4 bg-muted rounded w-32" }), _jsx("div", { className: "h-3 bg-muted rounded w-24" })] })] }), _jsxs("div", { className: "text-right space-y-2", children: [_jsx("div", { className: "h-4 bg-muted rounded w-20" }), _jsx("div", { className: "h-3 bg-muted rounded w-16" })] })] }) }, i))) })] }));
}
export function SkeletonChart() {
    return (_jsx("div", { className: "bg-card border border-border rounded-lg p-6", children: _jsxs("div", { className: "animate-pulse space-y-4", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("div", { className: "h-6 bg-muted rounded w-1/3" }), _jsxs("div", { className: "flex gap-2", children: [_jsx("div", { className: "h-8 bg-muted rounded w-16" }), _jsx("div", { className: "h-8 bg-muted rounded w-16" })] })] }), _jsx("div", { className: "h-64 bg-muted rounded-lg" }), _jsx("div", { className: "flex justify-center gap-6", children: Array.from({ length: 4 }).map((_, i) => (_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "w-3 h-3 bg-muted rounded-full" }), _jsx("div", { className: "h-4 bg-muted rounded w-16" })] }, i))) })] }) }));
}
