import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Routes, Route, Navigate } from 'react-router-dom';
import { AuthProvider } from './contexts/auth-context';
import { SidebarProvider } from './contexts/sidebar-context';
import { ErrorBoundary } from './components/error-boundary';
import { Toaster } from './components/ui/toaster';
import { Toaster as SonnerToaster } from './components/ui/sonner';
import Layout from './components/layout';
import HomePage from './pages/home';
import Dashboard from './pages/dashboard';
import Accounting from './pages/accounting';
import Sales from './pages/sales';
import Expenses from './pages/expenses';
import PurchaseOrders from './pages/purchase-orders';
import AccountsPayable from './pages/accounts-payable';
import EnhancedAccountsPayable from './pages/enhanced-accounts-payable';
import Banking from './pages/banking';
import Inventory from './pages/inventory';
import Reports from './pages/reports';
import Settings from './pages/settings';
import AIInsights from './pages/ai-insights';
import EnhancedTransactionProcessing from './pages/enhanced-transaction-processing';
import EnhancedJournalManagement from './pages/enhanced-journal-management';
import CreditNotes from './pages/credit-notes';
import PeriodClose from './pages/period-close';
import RevenueRecognition from './pages/revenue-recognition';
import FixedAssets from './pages/fixed-assets';
import LlamaAI from './pages/llama-ai';
import Tax from './pages/tax';
import TaxCalculation from './pages/tax-calculation';
import Clients from './pages/clients';
import Security from './pages/security';
import Companies from './pages/companies';
import Help from './pages/help';
import FinancialReports from './pages/financial-reports';
import JournalNew from './pages/journal-new';
import BudgetManagement from './pages/budget-management';
import Documents from './pages/documents';
import POS from './pages/pos';
import JournalHub from './pages/journal-hub';
import UnifiedApprovalHub from './pages/unified-approval-hub';
import SupplierPortal from './pages/supplier-portal';
import Login from './pages/auth/login';
import Register from './pages/auth/register';
import Unauthorized from './pages/unauthorized';
function App() {
    return (_jsx(ErrorBoundary, { children: _jsx(AuthProvider, { children: _jsxs(SidebarProvider, { children: [_jsxs(Routes, { children: [_jsx(Route, { path: "/login", element: _jsx(Login, {}) }), _jsx(Route, { path: "/register", element: _jsx(Register, {}) }), _jsx(Route, { path: "/unauthorized", element: _jsx(Unauthorized, {}) }), _jsx(Route, { path: "/", element: _jsx(HomePage, {}) }), _jsx(Route, { path: "/reports", element: _jsx(Navigate, { to: "/dashboard/reports", replace: true }) }), _jsx(Route, { path: "/documents", element: _jsx(Navigate, { to: "/dashboard/documents", replace: true }) }), _jsxs(Route, { path: "/dashboard", element: _jsx(Layout, {}), children: [_jsx(Route, { index: true, element: _jsx(Dashboard, {}) }), _jsx(Route, { path: "accounting", element: _jsx(Accounting, {}) }), _jsx(Route, { path: "sales", element: _jsx(Sales, {}) }), _jsx(Route, { path: "pos", element: _jsx(POS, {}) }), _jsx(Route, { path: "journal-hub", element: _jsx(JournalHub, {}) }), _jsx(Route, { path: "approval-hub", element: _jsx(UnifiedApprovalHub, {}) }), _jsx(Route, { path: "supplier-portal", element: _jsx(SupplierPortal, {}) }), _jsx(Route, { path: "expenses", element: _jsx(Expenses, {}) }), _jsx(Route, { path: "purchase-orders", element: _jsx(PurchaseOrders, {}) }), _jsx(Route, { path: "accounts-payable", element: _jsx(AccountsPayable, {}) }), _jsx(Route, { path: "enhanced-accounts-payable", element: _jsx(EnhancedAccountsPayable, {}) }), _jsx(Route, { path: "banking", element: _jsx(Banking, {}) }), _jsx(Route, { path: "inventory", element: _jsx(Inventory, {}) }), _jsx(Route, { path: "reports", element: _jsx(Reports, {}) }), _jsx(Route, { path: "settings", element: _jsx(Settings, {}) }), _jsx(Route, { path: "ai-insights", element: _jsx(AIInsights, {}) }), _jsx(Route, { path: "enhanced-transaction-processing", element: _jsx(EnhancedTransactionProcessing, {}) }), _jsx(Route, { path: "enhanced-journal-management", element: _jsx(EnhancedJournalManagement, {}) }), _jsx(Route, { path: "credit-notes", element: _jsx(CreditNotes, {}) }), _jsx(Route, { path: "period-close", element: _jsx(PeriodClose, {}) }), _jsx(Route, { path: "revenue-recognition", element: _jsx(RevenueRecognition, {}) }), _jsx(Route, { path: "fixed-assets", element: _jsx(FixedAssets, {}) }), _jsx(Route, { path: "llama-ai", element: _jsx(LlamaAI, {}) }), _jsx(Route, { path: "tax", element: _jsx(Tax, {}) }), _jsx(Route, { path: "tax-calculation", element: _jsx(TaxCalculation, {}) }), _jsx(Route, { path: "clients", element: _jsx(Clients, {}) }), _jsx(Route, { path: "companies", element: _jsx(Companies, {}) }), _jsx(Route, { path: "security", element: _jsx(Security, {}) }), _jsx(Route, { path: "help", element: _jsx(Help, {}) }), _jsx(Route, { path: "help-support", element: _jsx(Help, {}) }), _jsx(Route, { path: "financial-reports", element: _jsx(FinancialReports, {}) }), _jsx(Route, { path: "financial-reporting", element: _jsx(FinancialReports, {}) }), _jsx(Route, { path: "budget-management", element: _jsx(BudgetManagement, {}) }), _jsx(Route, { path: "documents", element: _jsx(Documents, {}) }), _jsx(Route, { path: "journal/new", element: _jsx(JournalNew, {}) }), _jsx(Route, { path: "custom-report-builder", element: _jsx(Reports, {}) })] })] }), _jsx(Toaster, {}), _jsx(SonnerToaster, { position: "top-right" })] }) }) }));
}
export default App;
